### ISSUE TITLE
Review event ping format

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/telemetry-android#4]
```
{
  "v": 1,
  "clientId": "c1d14cc8-97ce-45a9-823e-0e780a5e167f",
  "seq": 9,
  "locale": "en-US",
  "os": "Android",
  "osversion": "25",
  "created": "2017-03-27",
  "tz": 120,
  "settings": {
    "pref_privacy_block_ads": "true",
    "pref_privacy_block_social": "true",
    "pref_privacy_block_other": "true",
    "pref_privacy_block_analytics": "false",
    "pref_performance_block_webfonts": "true",
    "pref_search_engine": "Yahoo"
  },
  "events": [
    [
      0,
      "action",
      "change",
      "setting",
      "pref_search_engine",
      {
        "to": "Yahoo"
      }
    ],
    [
      1345,
      "action",
      "change",
      "setting",
      "pref_privacy_block_analytics",
      {
        "to": "false"
      }
    ],
    [
      7499,
      "action",
      "change",
      "setting",
      "pref_privacy_block_other",
      {
        "to": "true"
      }
    ],
    [
      8056,
      "action",
      "change",
      "setting",
      "pref_privacy_block_social",
      {
        "to": "true"
      }
    ],
    [
      12791,
      "action",
      "type_url",
      "search_bar",
      null,
      null,
      null
    ],
    [
      20723,
      "action",
      "type_query",
      "search_bar",
      null,
      null,
      null
    ],
    [
      23422,
      "action",
      "click",
      "erase_button",
      null,
      null,
      null
    ]
  ]
}
```

**Comment by pocmo** [comment]
@fbertsch That's an event ping that was generated after using Focus shortly. Does this look good to you? Any obvious issues?

**Comment by fbertsch** [comment]
@pocmo Just a few questions:

1. Event format requires `[Timestamp, category, method, object]` but the rest are optional. So we don't need those `null`s in the events.

2. Can created be a timestamp?

3. Will our first event always have time 0, and everything after relative to that time?

**Comment by pocmo** [comment]
@fbertsch 

> Event format requires [Timestamp, category, method, object] but the rest are optional. So we don't need those nulls in the events.

Ah, okay. I'm going to update the code accordingly.

> Can created be a timestamp?

I was following the core ping here:
https://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/data/core-ping.html

But I can update that to whatever we need here. UNIX timestamp in milliseconds?

> Will our first event always have time 0, and everything after relative to that time?

Yeah, that's a side effect from the current implementation. Does milliseconds since "app start" make more sense? (Technically it would be "process" start - which can span multiple app starts).

**Comment by fbertsch** [comment]
>But I can update that to whatever we need here. UNIX timestamp in milliseconds?

UNIX timestamp is fine. This will be helpful in case we want to compare between sessions for any reason (e.g. spent X time outside of the App).

> Does milliseconds since "app start" make more sense? (Technically it would be "process" start - which can span multiple app starts).

No, I kind of like it this way. I don't see any added benefit from having them possible span multiple app starts; if we need to compare between app starts we can look at submission or creation time.

**Comment by pocmo** [comment]
@fbertsch Here's a new version of the ping.

```
{
  "tz": 120,
  "seq": 21,
  "created": 1490698413319,
  "locale": "en-US",
  "settings": {
    "pref_privacy_block_ads": "false",
    "pref_privacy_block_social": "true",
    "pref_search_engine": "DuckDuckGo",
    "pref_privacy_block_analytics": "true",
    "pref_performance_block_webfonts": "true",
    "pref_privacy_block_other": "true"
  },
  "clientId": "f0d6f5ff-ca2e-4059-9fad-1ee0f9124cca",
  "v": 1,
  "osversion": "25",
  "os": "Android",
  "events": [
    [
      0,
      "action",
      "type_url",
      "search_bar"
    ],
    [
      5237,
      "action",
      "change",
      "setting",
      "pref_privacy_block_ads",
      {
        "to": "false"
      }
    ],
    [
      6508,
      "action",
      "change",
      "setting",
      "pref_privacy_block_social",
      {
        "to": "true"
      }
    ],
    [
      7006,
      "action",
      "change",
      "setting",
      "pref_privacy_block_other",
      {
        "to": "true"
      }
    ],
    [
      12008,
      "action",
      "change",
      "setting",
      "pref_search_engine",
      {
        "to": "DuckDuckGo"
      }
    ],
    [
      14622,
      "action",
      "click",
      "erase_button"
    ],
    [
      20699,
      "action",
      "type_query",
      "search_bar"
    ]
  ]
}
```

> Will our first event always have time 0, and everything after relative to that time?

I just noticed that this will heavily depend on the time when the ping is created/sent currently. Right now I use the time of the first event to calculate an offset for the next events. However it's possible that we create a ping (the user leaves the app) and the app process continues to live until the app is resumed again. In this situation the next ping would have events that start not at 0 but still with an offset calculated from the last ping. I could reset the start time whenever a ping is created/sent though.

**Comment by fbertsch** [comment]
> I just noticed that this will heavily depend on the time when the ping is created/sent currently. Right now I use the time of the first event to calculate an offset for the next events. However it's possible that we create a ping (the user leaves the app) and the app process continues to live until the app is resumed again. In this situation the next ping would have events that start not at 0 but still with an offset calculated from the last ping. I could reset the start time whenever a ping is created/sent though.

I think that scheme is fine, just as long as we're consistent and have a solid understanding of how we got the numbers.

I'm going to verify with Barbara one last time that she doesn't see any need for any further dimensions that we would possibly want to break users down by. Other than that this looks great!
