### ISSUE TITLE
Add 'device' and 'arch' to mobile-event ping

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/telemetry-android#58]
Two new optional fields are being added to the focus-event ping; `device` and `arch`

See: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/101

**Comment by justindarc** [comment]
CC: @pocmo

**Comment by pocmo** [comment]
@justindarc Thank you for filing this. Aren't those in the core ping already?

**Comment by justindarc** [comment]
They are, yes. We are looking to add them to `focus-event` and `mobile-event` though to make it easier to query by device type (i.e. iPhone vs. iPad). This is technically achievable today if we join in the core ping data, but we think this is an important enough detail to add into the event pings directly.

**Comment by mcomella** [comment]
#60 has some code for this.

**Comment by pocmo** [comment]
Moved: https://github.com/mozilla-mobile/android-components/issues/119
