### ISSUE TITLE
Implement MobileEventPing

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/telemetry-android#59]
See:
https://github.com/mozilla-mobile/telemetry-ios/issues/78

And:
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/mobile-event/mobile-event.1.schema.json

It's a clone of focus-event but avoiding "Focus" in the name.

**Comment by mcomella** [comment]
Note: moving existing products (Focus, Rocket) is blocked on server so product doesn't have to have a separate query to query historical data: https://bugzilla.mozilla.org/show_bug.cgi?id=1426481

**Comment by mcomella** [comment]
Note that we'll need to figure out how to upload the telemetry library to JCenter, even though Sebastian owns it: https://bintray.com/pocmo/Mozilla-Mobile/telemetry Not that we have our own bintray org though: https://bintray.com/mozilla-mobile

**Comment by mcomella** [comment]
#63 must also be implemented before we can switch to mobile-event.
