### ISSUE TITLE
Add nicer API for adding event extras

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/telemetry-android#6]
Currently when adding an event with extras you have to pass a `Map` to the `create()` method of `TelemetryEvent`. That's clunky. Let's add something nicer that allows us to enforce the limits too (See #5).

Maybe some chaining?

```
TelemetryEvent event = create(..mandatory fields..)
    .extra(key, value)
    .extra(key, value);
```

**Comment by kination** [comment]
@pocmo Looks like chaining like above has been implemented. Are you thinking about other more options for this?
