### ISSUE TITLE
Extra max key length should be asserted, not silently truncated

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/telemetry-android#66]
Currently, [we do this](https://github.com/mozilla-mobile/telemetry-android/blob/b4d7c5790dcc7e2e6fe71a655749d783ebd3dd76/telemetry/src/main/java/org/mozilla/telemetry/event/TelemetryEvent.java#L111):
```java
    public TelemetryEvent extra(String key, String value) {
        ...
        extras.put(StringUtils.safeSubstring(key, 0, MAX_LENGTH_EXTRA_KEY),
                StringUtils.safeSubstring(value, 0, MAX_LENGTH_EXTRA_VALUE));

        return this;
}
```

This sucks as a user of the library because:
- I enter a > max length key
- I enter in the docs that the key is the > max length key
- When looking at the dashboards, I won't be able to find the event because I'm looking for a string that was silently truncated without my knowledge

We should assert that the key lengths are not greater than the max size as they're passed to the library, or otherwise indicate to the user of the lib, that this is happening so they can set their docs accordingly.

**Comment by pocmo** [comment]
Moved: https://github.com/mozilla-mobile/android-components/issues/118
