### ISSUE TITLE
Implement mobile-metrics ping type

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/telemetry-android#68]
Why
- needs to be done by 6.0
- considered a lot of work and we need to get a heads-start

https://docs.google.com/document/d/1q2V45_fyzm_DGaCos34QEQimsodYJMJCq5Ix-ys9KkE/edit

**Comment by pocmo** [comment]
See https://github.com/mozilla-mobile/focus-android/issues/2347 for some details.

**Comment by fbertsch** [comment]
@pocmo schema is ready [0], so you should be able to start sending pings and viewing them using the CEP [1].

[0] https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/mobile-metrics/mobile-metrics.1.schema.json
[1] https://docs.telemetry.mozilla.org/cookbooks/view_pings_cep.html

**Comment by pocmo** [comment]
Moved: https://github.com/mozilla-mobile/android-components/issues/113
