### ISSUE TITLE
Event strings can be up to 50 characters

### ISSUE THREAD

**Issue by justindarc** [mozilla-mobile/telemetry-android#69]
There are currently several constraints on strings in Events:

https://github.com/mozilla-mobile/telemetry-android/blob/master/telemetry/src/main/java/org/mozilla/telemetry/event/TelemetryEvent.java#L29-L35

To keep things simple and allow for greater flexibility in naming, all strings can actually be up to 50 characters in length.

This is based on a Slack conversation I had with @fbertsch and we will be doing the same in mozilla-mobile/telemetry-ios.

**Comment by mcomella** [comment]
fwiw, I think the max String length should be asserted in some way (e.g. return a boolean to the caller?): it's a bad experience as a user of the library to lose data because your strings happen to be too long so were only partially uploaded. See #66.

**Comment by justindarc** [comment]
Definitely. We just ran into this very issue in Firefox for iOS. We can't differentiate between two different events because the names were truncated silently :-/

**Comment by pocmo** [comment]
Moved: https://github.com/mozilla-mobile/android-components/issues/118
